# Generated by Django 3.2 on 2022-01-20 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_room_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='room_liks', to=settings.AUTH_USER_MODEL),
        ),
    ]
